troiswa_back_contact:
    path: /contact
    defaults: { _controller:TroiswaBackBundle:Statics:contact}

troiswa_back_feedback:
    path: /feedback
    defaults: { _controller:TroiswaBackBundle:Statics:feedback}

troiswa_back_statics:
  path: /statics
  defaults: { _controller:TroiswaBackBundle:Statics:cgv}

troiswa_back_equipes:
  path: /equipes
  defaults:
    _controller: FrameworkBundle:Template:template
    template: "TroiswaBackBundle:Main:equipe.html.twig"