trois_back_User:
  path: /
  defaults: { _controller:TroiswaBackBundle:User:User}

trois_back_User_info:
  path: /information/{idprod}
  defaults: { _controller:TroiswaBackBundle:User:User_info}
  requirements:
    idCat: \d+

trois_back_User:
    path: /add
    defaults: { _controller:TroiswaBackBundle:User:adduser}

trois_back_User_editer:
    path: /editer/{idprod}
    defaults: { _controller:TroiswaBackBundle:User:edite }
    requirements:
        idCat: \d+

trois_back_User_supprimer:
    path: /supprimer/{idprod}
    defaults: { _controller:TroiswaBackBundle:User:supp }
    requirements:
        idCat: \d+