troiswa_back_User:
  path: /
  defaults: { _controller:TroiswaBackBundle:User:index}

troiswa_back_User_info:
  path: /information/{id}
  defaults: { _controller:TroiswaBackBundle:User:show}
  requirements:
    idCat: \d+

troiswa_back_User_add:
    path: /add
    defaults: { _controller:TroiswaBackBundle:User:new}

troiswa_back_User_create:
    path: /create
    defaults: { _controller:TroiswaBackBundle:User:create}
    methods: POST

troiswa_back_User_editer:
    path: /editer/{id}
    defaults: { _controller:TroiswaBackBundle:User:edit }
    requirements:
        idCat: \d+

troiswa_back_user_update:
    path:     /{id}/update
    defaults: { _controller: "TroiswaBackBundle:User:update" }
    methods:  [POST, PUT]

troiswa_back_User_supprimer:
    path: /supprimer/{id}
    defaults: { _controller:TroiswaBackBundle:User:delete }
    requirements:
        idCat: \d+

