security:

    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Troiswa\BackBundle\Entity\User:
          algorithm: bcrypt
          cost: 13


        FOS\UserBundle\Model\UserInterface: bcrypt





    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_COMMERCIAL, ROLE_ALLOWED_TO_SWITCH]
        ROLE_COMMERCIAL: [ROLE_CLIENT]
        ROLE_CLIENT: [ROLE_USER]






    providers:
      in_memory:
        memory:
          users: # Utilisateur en mémoire
            admin: #nom d'utilsateur
              password: motdepasse #mot de passe pour l'utilisateur admin
              roles: ROLE_ADMIN
            toto: { password: bidule,roles: ROLE_USER} #utilisateur toto avec le mot de passe bidule


      provider_back:
          #entity : { class: TroiswaBackBundle:User, property: pseudo }
          #entity: { class: TroiswaBackBundle:User, property: email }
          # Visualiser la méthode loadUserByUsername dans UserRepository pour mieux comprendre
          entity: { class: TroiswaBackBundle:User }


      fos_userbundle:
          id: fos_user.user_provider.username






    firewalls:
      dev:
        pattern: ^/(_(profiler|wdt|error)|css|images|js)/
        security: false

      front_login:
        pattern: ^/login$
        anonymous: true


      main:
        pattern: ^/
        form_login:
          provider: fos_userbundle
          csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4

        logout:       true
        anonymous:    false




      login_firewall:
        pattern: ^/admin/login$
        anonymous: true

      administration:
        pattern: ^/admin  #toutes les url ki commence par admin va les bloquer
        anonymous: false
        #http_basic:    #va creer une ptite boite de dialog
          #realm: "Attention zone réservée"
          #provider: in_memory   #ou allez chercher les utilisateurs
          #provider: provider_back
        form_login:
            check_path: troiswa_back_login_check
            login_path: troiswa_back_login
            csrf_provider: security.csrf.token_manager
            default_target_path: troiswa_back_administration
            always_use_default_target_path: true
        remember_me:
            key: "%secret%"
            lifetime: 172800 # 2 jours
            path: / # accessible sur toutes les urls
            domain: ~ #valeur par défaut : accessible partout sur mon site
        logout:
            path: troiswa_back_logout
            target: /admin/login


        provider: provider_back

       # switch_user: { role: ROLE_ADMIN, parameter: _want_to_be_this_user }
        switch_user: { role: ROLE_ADMIN }





    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }


        # seul l'administrateur à accès aux pages produit
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_CLIENT }

