<?php

namespace Troiswa\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductCoverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCartRepository extends EntityRepository
{

}