<?php

namespace Troiswa\BackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * brandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class brandRepository extends EntityRepository

{
    public function findAllMarque()
    {
        $query=$this->getEntityManager()
                     ->createQuery(
                "select bran
                        from TroiswaBackBundle:Brand bran"
            );
        return $query->getResult();
    }

    /*
    public function findAllProductwithMarque()
    {
        $query=$this->getEntityManager()->createQuery("
                       Select bran,prod
                       from TroiswaBackBundle:Brand bran
                       LEFT JOIN bran.categ cat");
        return $query->getResult();
    }  */
}
